### ISSUE TITLE
Minor issues in gameplay

### ISSUE THREAD

**Issue by codemann8** [cassidoxa/ALttPEntranceRandomizer#7] opened 2019-08-17 09:45 UTC
I ran another 2-player Inverted MW today.  Definitely was a great improvement since the last commit.  I have only a few small issues to report.  The logic seemed to work out much better than the last one. @cassidoxa, tagging in hopes you'll be notified.

1) Mirror Bonk Inverted Related Issues: A) If you visit the Bombos Tablet and mirror back into Mire area from just slightly down and right from that tablet, it'll let you mirror into the side of a mountain, with the inability to mirror back since it's inside the mountain side.  I suggest having this small mountain leveled so this cannot happen. See Vod P2 @ 1:29:20
B) If you walk up by the courtyard of Hyrule Castle, with your character's left foot in the center of the 2nd heart (from the top, in the main walkway towards HC entrance) and mirror from that point, you'll end up in the middle of the pyramid and doesn't bonk you back.  See Vod P2 @ 2:46:30

2) Slight XY character positional issue when leaving Ganon after falling during the fight.  When you go back on the OW, the character seems like it should be shifted 8 pixels to the left.  It appears as he's exiting, he's exiting partially thru the bush.  See Vod P1 @ 3:30:20

3) When you get a Game Over to Ganon, and you haven't beat Aga1 (and I also assume if you beat Aga1 but also don't have mirror), it doesn't start you back above Ganon's hole, it instead gives you the standard 3 places to start (as if you saved and quit, and loaded up a previous save). See Vod P1 @ 3:31:30

Vod Player 1: https://www.twitch.tv/videos/468153843
Vod Player 2: https://www.twitch.tv/videos/468158166

**Comment by cassidoxa** [comment] 2019-08-17 16:40
Thanks codemann. The mirror bonking issues are problems with the ROM upstream. In Mire specifically you should mirror bonk because letting the player walk around up there would allow them to screen transition out of bounds. I'm not sure why dying to Ganon doesn't put you on the castle ledge. I'd have to test it. The pyramid exit is probably a wrong byte being written in the inverted ER code. I'll look into it but it seems to work correctly if entrances are shuffled. When multiworld for the VT randomizer comes out, that's what will be primarily used for inverted multiworlds with vanilla entrances and it should be correct there. It may or may not be fixed but if it's just one byte for Link's X position then I'll probably push an update soon-ish.

**Comment by codemann8** [comment] 2019-08-17 17:22
I guess that was my concern, that it didn't mirror bonk and let you clip into the side of the mountain, but if it's upstream, you'd know better as to which source that bug report should be sent to, as I'm not entirely positive what the true source is.

**Comment by cassidoxa** [comment] 2019-08-17 17:30
The base rando ROM source is here: https://github.com/KatDevsGames/z3randomizer. I can file a report in a bit. Also I fixed the vanilla pyramid exit, turns out it was indeed one hex digit off.

**Comment by cassidoxa** [comment] 2019-08-17 17:59
On further investigation I think what may have happened was I built the wrong ROM version myself and used it as a base ROM for inverted ER. I can't seem to reproduce these on a regular inverted from alttpr.com

**Comment by cassidoxa** [comment] 2019-08-23 14:29
Ok, I figured out why the player wasn't spawning on HC ledge after a Ganon death and fixed it. Still not sure about the mirror bonk thing. I may have neglected to change a byte that controls that, but it looks like that's part of the base ROM which should be activated in inverted mode. I'll keep looking into that, but closing for now.

**Closed as completed by cassidoxa** 2019-08-23 14:29 UTC

**Comment by cassidoxa** [comment] 2019-08-24 03:02
Mirror bonking is fixed. Wasn't the ROM, the blame lies squarely on me. Some byte that I don't even know what it does exactly was written wrong.
